# Workflow to run CIT on derecho via self-hosted runner

name: CIT on derecho

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "feature_CIT" branch
  pull_request:
    types: [labeled]
    branches: 
      - develop
      - feature*
      - main*
      - bugfix_*
    paths-ignore:
      #- 'docs/**'
      - '.github/pull_request_template.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '**/README.md'
      - '**/LICENSE.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_test"
  build_and_test:
    # Only do the actions when merged or manually run
    if: github.event.label.name == 'run-pr-tests' || github.event_name == 'workflow_dispatch'
    # The type of runner that the job will run on
    runs-on: shr-derecho

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  v2 or v4? (Julie's example shows v2)
      - uses: actions/checkout@v4

      # Run the CI framework
      - name: Run CI framework
        run: |
          source /glade/work/ishitas/python_envs/py_derecho/bin/activate
          cd /glade/work/fasteddyrt/repos/FastEddy-CI/tests
          python3 run_tests.py --suite comprehensive -c config/workflow_top.yml

      # Commenting out uploads of test reports.  Not needed and creates unwanted coupling between these and 
      # what test suite is run above, and/or what tests are in it.
      #- name: Upload test report for Example01_NBL
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-1
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example01_NBL/output/Example01_NBL_report.html

      #- name: Upload test report for Example02_CBL
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-2
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example02_CBL/output/Example02_CBL_report.html

      #- name: Upload test report for Example03_SBL
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-3
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example03_SBL/output/Example03_SBL_report.html

      #- name: Upload test report for Example04_BOMEX
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-4
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example04_BOMEX/output/Example04_BOMEX_report.html

      #- name: Upload test report for Example05_CANOPY
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-5
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example05_CANOPY/output/Example05_CANOPY_report.html

      #- name: Upload test report for Example06_OFFSHORE
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-6
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example06_OFFSHORE/output/Example06_OFFSHORE_report.html

      #- name: Upload test report for Example07_DISPERSION_CBL
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-7c
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example07_DISPERSION_CBL/output/Example07_DISPERSION_CBL_report.html

      #- name: Upload test report for Example07_DISPERSION_SBL
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-report-7s
      #    path: /glade/derecho/scratch/fasteddyrt/fasteddy_results/Example07_DISPERSION_SBL/output/Example07_DISPERSION_SBL_report.html
      
      # Runs a simple script that appends the datetime to a file
      - name: Record the datetime of the run
        run: |
          echo Append datetime to a file
          /glade/work/fasteddyrt/actions-runner/appendDatetimeRun.sh
          
