# A manually dispatched workflow to keep the self-hosted runner alive.  If idle for 14 days, they will time out and go away.

name: Keep Alive WF

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "feature_CIT" branch
  #pull_request:
  #  types: [labeled]
  #  branches: 
  #    - feature*
  #  paths-ignore:
  #    #- 'docs/**'
  #    - '.github/pull_request_template.md'
  #    - '.github/ISSUE_TEMPLATE/**'
  #    - '**/README.md'
  #    - '**/LICENSE.md'
      
  # Allows you to run this workflow manually from the Actions tab, or from github CLI, which will be used for this workflow (from cron).
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "keep_alive"
  keep_alive:
    # Only do the actions when manually run
    #if: github.event.label.name == 'run-pr-tests' || github.event_name == 'workflow_dispatch'
    if: github.event_name == 'workflow_dispatch'
    # The type of runner that the job will run on
    runs-on: shr-derecho

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!  Stay alive!
      
      # Runs a simple script that appends the datetime to a file
      - name: Record the datetime of the run
        run: |
          echo Append datetime to a file
          /glade/work/fasteddyrt/actions-runner/appendDatetimeRun.sh
